definitions:
  models.Car:
    properties:
      brand:
        type: string
      id:
        type: integer
      model:
        type: string
      name:
        type: string
      price:
        type: number
      year:
        type: integer
    type: object
  models.Errors:
    properties:
      details:
        type: string
      error:
        type: string
    type: object
host: localhost:3015
info:
  contact: {}
  description: This is an API to serve car inventory applications
  title: CarInventory
  version: "1.0"
paths:
  /cars:
    post:
      consumes:
      - application/json
      description: Add a new car to the inventory
      parameters:
      - description: Add car
        in: body
        name: cars
        required: true
        schema:
          $ref: '#/definitions/models.Car'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Car'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Errors'
      summary: Create a new car
      tags:
      - cars
  /cars/{id}:
    get:
      consumes:
      - application/json
      description: Get a car from the inventory
      parameters:
      - description: car id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Car'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Errors'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Errors'
      summary: Get a car
      tags:
      - cars
swagger: "2.0"
